
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - examples.example.com
  resources:
  - examplecrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examples.example.com
  resources:
  - examplecrs/finalizers
  verbs:
  - update
- apiGroups:
  - examples.example.com
  resources:
  - examplecrs/status
  verbs:
  - get
  - patch
  - update
